version: "3"
services:
    web:
        build: .
        container_name: celsius3_web
        network_mode: host
        volumes:
          - .:/var/www/html

    mysql:
        image: mysql:5
        container_name: celsius3_mysql
        network_mode: host
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "celsius3"
            MYSQL_USER: "celsius3"
            MYSQL_PASSWORD: "celsius3"

    elasticsearch:
        image: elasticsearch:2.3.1
        container_name: celsius3_elasticsearch
        network_mode: host

    redis:
        image: redis:alpine
        container_name: celsius3_redis
        network_mode: host

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: celsius3_phpmyadmin
#        environment:
#              PMA_PORT: 3306
#              PMA_HOST: localhost
#              PMA_USER: root
#              PMA_PASSWORD: root
#        ports:
#          - "8080:80"
#        depends_on:
#          - mysql
