version: "3"
services:
    web:
        build: .
        container_name: celsius3_web
        network_mode: host
        volumes:
          - .:/var/www/html

    mysql:
        image: mysql:5
        container_name: celsius3_mysql
        network_mode: host
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: celsius3
        volumes:
          - ./.docker/mysql:/var/lib/mysql

    elasticsearch:
        image: elasticsearch:2.3.1
        container_name: celsius3_elasticsearch
        network_mode: host
        volumes:
          - ./.docker/elasticsearch/data:/usr/share/elasticsearch/data

    redis:
        image: redis:alpine
        container_name: celsius3_redis
        network_mode: host
        volumes:
          - ./.docker/redis:/data

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: celsius3_phpmyadmin
        ports:
          - "8080:80"
        links:
          - mysql:db
