version: "3"
services:
    web:
        build: .
        container_name: celsius3_web
        network_mode: host
        volumes:
          - .:/var/www/html
        depends_on:
          - mysql
          - elasticsearch
          - redis

    mysql:
        image: mysql:5
        container_name: celsius3_mysql
        network_mode: host
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "celsius3"
            MYSQL_USER: "celsius3_usr"
            MYSQL_PASSWORD: "celsius3_pass"

    elasticsearch:
        image: elasticsearch:2.3.1
        container_name: celsius3_elasticsearch
        network_mode: host

    redis:
        image: redis:alpine
        container_name: celsius3_redis
        network_mode: host

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: celsius3_phpmyadmin
        ports:
          - 8000:80
        environment:
          PMA_HOST: "172.17.0.1"
          PMA_PORT: "3306"
          PMA_USER: "celsius3_usr"
          PMA_PASSWORD: "celsius3_pass"
        depends_on:
          - mysql
