imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    trust_proxy_headers: false
    default_locale: en
    translator:      { fallback: en }
    secret:          %secret%
    router:          
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         ~
        
# Monolog Configuration
monolog:
    handlers:
        custom:
            type:                service
            id:                  mongodb_logger_wrapper_handler

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    bundles:        []
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8
#
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
        
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongodb_host%:%mongodb_port%
            options:
                connect: true
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    spool: { type: memory }
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: CelsiusCelsius3Bundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
  
fos_user:
    db_driver: mongodb # 'orm', 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Celsius\Celsius3Bundle\Document\BaseUser
    registration:
        form:
            type: celsius_celsius3bundle_registration
            
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
                - { name: twig.extension }
  
    # Setea el codigo de Order
    counter_listener:
        class: Celsius\Celsius3Bundle\Listener\CounterListener
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
            
    # Crea la Configuration inicial de una Instance
    configuration_listener:
        class: Celsius\Celsius3Bundle\Listener\ConfigurationListener
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
    
    # Formulario de registro personalizado
    celsius_celsius3bundle.registration.form.type:
        class: Celsius\Celsius3Bundle\Form\Type\RegistrationFormType
        arguments: ["@service_container", %fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: celsius_celsius3bundle_registration }
    
    # Type con DataTransformer para setear el usuario en un formulario
    celsius_celsius3bundle.form.user_selector:
        class: Celsius\Celsius3Bundle\Form\Type\UserSelectorType
        arguments: ["@doctrine.odm.mongodb.document_manager"]
        tags:
            - { name: form.type, alias: user_selector }
    
    # Type con DataTransformer para setear la instancia en un formulario
    celsius_celsius3bundle.form.instance_selector:
        class: Celsius\Celsius3Bundle\Form\Type\InstanceSelectorType
        arguments: ["@doctrine.odm.mongodb.document_manager"]
        tags:
            - { name: form.type, alias: instance_selector }
    
    celsius_celsius3bundle.security.login_listener:
        class: Celsius\Celsius3Bundle\Listener\LoginListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
    celsius_celsius3bundle.security.authentication_handler:
        class: Celsius\Celsius3Bundle\Handler\AuthenticationHandler
        arguments: ["@service_container"]
        
    mongodb_logger_wrapper_handler:
        class: Celsius\Celsius3Bundle\Handler\MongoDBWrapperHandler
        arguments: ["@service_container"]
            
    login_logging_pointcut:
        class: Celsius\Celsius3Bundle\Aop\LoginLoggingPointcut
        tags:
            - { name: jms_aop.pointcut, interceptor: login_logging_interceptor }
            
    login_logging_interceptor:
        class: Celsius\Celsius3Bundle\Aop\LoginLoggingInterceptor
        arguments: ["@service_container", "@doctrine.odm.mongodb.document_manager"]
        
    menu.voter.exact:
        class: Celsius\Celsius3Bundle\Voter\ExactRequestVoter
        arguments: ["@service_container"]
        tags:
            - { name: knp_menu.voter }    
    
#    menu.voter.request:
#        class: Celsius\Celsius3Bundle\Voter\RequestVoter
#        arguments: ["@service_container"]
#        tags:
#            - { name: knp_menu.voter }
            
parameters:
    max_per_page: 10
    mongodb_host: localhost
    mongodb_port: 27017
    mongodb_database: celsius
    mongodb_database_test: celsius_test
    mongodb_log_collection: Log
    
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop
    
jms_i18n_routing:
    default_locale: es
    locales: [es, en, pt]
    strategy: prefix_except_default
    
knp_menu:
    twig:
        template: CelsiusCelsius3Bundle:Layout:knp_menu.html.twig
