imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            excluded_404s:
                - ^/phpmyadmin
                - ^/tutoriales
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
            formatter: monolog_formatter
        console:
            type:  console

services:
    assetic.worker.cache_busting:
        class: Assetic\Factory\Worker\CacheBustingWorker
        public: false
        tags:
            - { name: assetic.factory_worker }
