imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    trusted_proxies: ['127.0.0.1', '10.0.0.1'] # a list of proxy IPs you trust
    default_locale: es
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        notification_host: %notification_host%
        notification_port: %notification_port%
        notification_limit: %notification_limit%
    form:
        resources:
            - 'Celsius3CoreBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    bundles:        [Celsius3CoreBundle,TwigBundle]
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        less:
            node: %node_path%
            node_paths: [%node_modules%]
            apply_to:   "\.less$"
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
    assets:
        bootstrap:
            inputs:
                - "bundles/celsius3core/components/bootstrap/dist/css/bootstrap.css"
            filters:
                - cssrewrite
        font_awesome:
            inputs:
                - "bundles/celsius3core/components/fontawesome/css/font-awesome.min.css"
            filters:
                - cssrewrite
        select2:
            inputs:
                - "bundles/celsius3core/components/select2-ng/select2.css"
            filters:
                - cssrewrite
        select2-bootstrap-css:
            inputs:
                - "bundles/celsius3core/components/select2-bootstrap-css/select2-bootstrap.css"
            filters:
                - cssrewrite

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                metadata_cache_driver: redis
                query_cache_driver: redis
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    string_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        IFNULL: DoctrineExtensions\Query\Mysql\IfNull
                        DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                
# Swiftmailer Configuration
swiftmailer:
    spool:
        type: file
        path: "%kernel.root_dir%/spool"
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: Celsius3CoreBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm # 'orm', 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Celsius3\CoreBundle\Entity\BaseUser
    profile:
        form:
            type: celsius3_corebundle_profile
    registration:
        form:
            type: celsius3_corebundle_registration
    change_password:
        form:
            validation_groups:  [ChangePassword]
    service:
        mailer: celsius3_core.fos_mailer.custom

services:
    # Formulario de registro personalizado
    registration.form.type:
        class: Celsius3\CoreBundle\Form\Type\RegistrationFormType
        arguments: ["@service_container", %fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: celsius3_corebundle_registration }

    profile.form.type:
        class: Celsius3\CoreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: celsius3_corebundle_profile }

    jms_serializer.metadata.doctrine_type_driver:
        class:        %jms_serializer.metadata.doctrine_type_driver.class%
        public:       false
        arguments:    ["@jms_serializer.metadata.chain_driver", "@doctrine"]

    jms_serializer.metadata.doctrine_object_constructor:
        class:        %jms_serializer.doctrine_object_constructor.class%
        public:       false
        arguments:    ["@doctrine", "@jms_serializer.unserialize_object_constructor"]
        
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
            
    kernel.listener.command_dispatch:
        class: Celsius3\CoreBundle\EventListener\ConsoleLoggingListener
        arguments:
            logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: console.exception }
            - { name: kernel.event_listener, event: console.terminate }
    
    oauth_event_listener:
        class:  Celsius3\ApiBundle\EventListener\OAuthEventListener
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            userManager: "@fos_user.user_manager"
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
            - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop

jms_i18n_routing:
    default_locale: es
    locales: [es, en, pt]
    strategy: prefix

fos_message:
    db_driver: orm
    thread_class: Celsius3\MessageBundle\Entity\Thread
    message_class: Celsius3\MessageBundle\Entity\Message
    provider: celsius3_message.provider.default
    new_thread_form:
        type:               celsius3_message.new_thread_form.type.custom
        handler:            fos_message.new_thread_multiple_form.handler
        model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
    reply_form:
        type:               celsius3_message.reply_form.type.custom

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sluggable: true
            softdeleteable: true

genemu_form:
    select2: ~
    autocomplete: ~
    tinymce:
        theme: modern

celsius3_notification:
    web_socket_server:
        port: %notification_port%        #The port the socket server will listen on
        host: %notification_host%   #(optional) The host ip to bind to
        zmq_port: %notification_zmq_port%
        zmq_host: %notification_zmq_host%

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        formats:
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

jms_serializer:
    metadata:
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "@Celsius3ApiBundle/Resources/config/serializer/fos"
            Celsius3CoreBundle:
                namespace_prefix: Celsius3\CoreBundle
                path: "@Celsius3ApiBundle/Resources/config/serializer/core"

sp_bower:
    install_on_warmup: true
    assetic:
        nest_dependencies: false
    bundles:
        Celsius3CoreBundle: ~

snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn: redis://localhost
        cache:
            type: predis
            alias: cache
            dsn: redis://localhost
    session:
        client: session
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default          # the name of your entity_manager connection
        result_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default

fos_oauth_server:
    db_driver: orm
    client_class: Celsius3\ApiBundle\Entity\Client
    access_token_class: Celsius3\ApiBundle\Entity\AccessToken
    refresh_token_class: Celsius3\ApiBundle\Entity\RefreshToken
    auth_code_class: Celsius3\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            supported_scopes: admin superadmin
            access_token_lifetime: 3600 # Una hora
            refresh_token_lifetime: 43200 # Un día
            auth_code_lifetime: 60 # Un minuto
            
knp_menu:
    twig:
        template: Celsius3CoreBundle:Default:knp_menu.html.twig