imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    trusted_proxies: ['127.0.0.1', '10.0.0.1'] # a list of proxy IPs you trust
    default_locale: es
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         ~

# Monolog Configuration
monolog:
    handlers:
        custom:
            type:                service
            id:                  celsius3_core.mongodb_logger_wrapper_handler

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        notification_host: %notification_host%
        notification_port: %notification_port%
        notification_limit: %notification_limit%
        chat_host: %chat_host%
        chat_port: %chat_port%
    form:
        resources:
            - 'Celsius3CoreBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    bundles:        [Celsius3CoreBundle]
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/lib/node_modules]
            apply_to:   "\.less$"
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongodb_host%:%mongodb_port%
            options:
                connect: true
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true
            mappings:
                gedmo_translatable:
                    type: annotation
                    prefix: Gedmo\Translatable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document"
                    alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_translator:
                    type: annotation
                    prefix: Gedmo\Translator\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Document"
                    alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_loggable:
                    type: annotation
                    prefix: Gedmo\Loggable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
                    alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_tree:
                    type: annotation
                    prefix: Gedmo\Tree\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
                    alias: GedmoTree # this one is optional and will default to the name set for the mapping
                    is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    spool:
        type: file
        path: "%kernel.root_dir%/spool"
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: Celsius3CoreBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: mongodb # 'orm', 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Celsius3\CoreBundle\Document\BaseUser
    profile:
        form:
            type: celsius3_corebundle_profile
    registration:
        form:
            type: celsius3_corebundle_registration
    service:
        mailer: celsius3_core.fos_mailer.custom

services:
    # Formulario de registro personalizado
    registration.form.type:
        class: Celsius3\CoreBundle\Form\Type\RegistrationFormType
        arguments: ["@service_container", %fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: celsius3_corebundle_registration }

    profile.form.type:
        class: Celsius3\CoreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: celsius3_corebundle_profile }
        
    jms_serializer.metadata.doctrine_type_driver:
        class:        %jms_serializer.metadata.doctrine_type_driver.class%
        public:       false
        arguments:    ["@jms_serializer.metadata.chain_driver", "@doctrine_mongodb"]
        
    jms_serializer.metadata.doctrine_object_constructor:
        class:        %jms_serializer.doctrine_object_constructor.class%
        public:       false
        arguments:    ["@doctrine_mongodb", "@jms_serializer.unserialize_object_constructor"]
    
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop

jms_i18n_routing:
    default_locale: es
    locales: [es, en, pt]
    strategy: prefix

fos_message:
    db_driver: mongodb
    thread_class: Celsius3\MessageBundle\Document\Thread
    message_class: Celsius3\MessageBundle\Document\Message
    provider: celsius3_message.provider.default
    new_thread_form:
        type:               celsius3_message.new_thread_form.type.custom
        handler:            fos_message.new_thread_multiple_form.handler
        model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
    reply_form:
        type:               celsius3_message.reply_form.type.custom

stof_doctrine_extensions:
    default_locale: %locale%
    mongodb:
        default:
            timestampable: true
            sluggable: true

genemu_form:
    select2: ~
    tinymce:
        theme: modern

celsius3_notification:
    web_socket_server:
        port: %notification_port%        #The port the socket server will listen on
        host: %notification_host%   #(optional) The host ip to bind to
        zmq_port: %notification_zmq_port%
        zmq_host: %notification_zmq_host%
        
celsius3_chat:
    web_socket_server:
        port: %chat_port%        #The port the socket server will listen on
        host: %chat_host%   #(optional) The host ip to bind to

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        formats:
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
        
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "@Celsius3ApiBundle/Resources/config/serializer/fos"
            Celsius3CoreBundle:
                namespace_prefix: Celsius3\CoreBundle
                path: "@Celsius3ApiBundle/Resources/config/serializer/core"