security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        migration:
            pattern: ^/migration/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: migration
            logout:
                path:   fos_user_security_logout
                target: directory
            anonymous:    false
        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                failure_handler: celsius3_core.security.authentication_failure_handler
                success_handler: celsius3_core.security.authentication_success_handler
                default_target_path: user_index
            logout:
                path:   fos_user_security_logout
                target: public_index
                success_handler: celsius3_core.security.logout_success_handler
            anonymous:    true
            switch_user: { role: ROLE_SUPER_ADMIN }

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        oauth_token:
            pattern:    ^/{url}/api/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/{url}/api/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        api:
            pattern:    ^/.*/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value

    access_control:
        - { path: ^/.*/api/oauth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/api/resource, roles: [ROLE_ADMIN, ROLE_SUPERADMIN] }
        - { path: ^/.*/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/user, role: ROLE_USER }
        - { path: ^/.*/admin, role: ROLE_ADMIN }
        - { path: ^/.*/superadmin, role: ROLE_SUPER_ADMIN }
        - { path: ^/.*/migration, role: ROLE_MIGRATOR }
        
    role_hierarchy:
        ROLE_LIBRARIAN:   ROLE_USER
        ROLE_ADMIN:       ROLE_LIBRARIAN
        ROLE_SUPER_ADMIN: ROLE_ADMIN
