services:
    celsius3_ticket.ticket_manager:
        class: Celsius3\TicketBundle\Manager\TicketManager
        arguments:
           - @service_container
    app.twig.extension:
             class: Celsius3\TicketBundle\Twig\AppExtension
             public: false
             arguments:
                - @service_container
             tags:
                 - { name: twig.extension }

